server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freight?character-Encoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zdf19941118.
