server:
  port: 8084

spring:
  application:
    name: traffic-wms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freight_wms?character-Encoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: zdf19941118.

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml