spring:
  application:
    name: traffic-web
  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace